config/routes.rb
Rails.application.routes.draw do
  get 'evaluations/new'
  get 'evaluations/create'
  root to: 'pages#home'

  resources :baskets do
    collection do
      get "top" => "baskets#top"
    end
    member do
      get "team_mate" => "baskets#team_mate"
    end
    resources :about, only: [:index]
    resources :contact, only: [:index]
    resources :evaluations, only: [:new, :create]
  end

  namespace :admin do
    resources :baskets, only: [:index]
  end

  get "admin/baskets" => "admin/baskets"

  # get 'about', to: 'pages#about'
  # get 'contact', to: 'pages#contact'
  # get 'baskets', to: 'baskets#index'
  # get 'baskets/:id', to: 'baskets#show', as: :basket
  # post 'baskets', to: 'baskets#create'

  # verb path, to: 'controller#action'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/basket.rb
class Basket < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  validates :position, presence: true
  has_many :evaluations, dependent: :destroy
end

app/models/evaluation.rb
class Evaluation < ApplicationRecord
  belongs_to :basket
end

app/controllers/admin/baskets_controller.rb
class Admin::BasketsController < ApplicationController

  def index
    @baskets = Basket.all
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/baskets_controller.rb
class BasketsController < ApplicationController

  before_action :set_basket, only: [:show, :edit, :update, :destroy, :team_mate]

  def top
    @top_baskets = Basket.where(average_score: 30)
  end

  def team_mate

  end

  def index
    @baskets = Basket.all
  end

  def show
  end

  def new
    @basket = Basket.new
  end

  def create
    @basket = Basket.new(basket_params)
    if @basket.save
      redirect_to basket_path(@basket)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @basket.update(basket_params)
    redirect_to basket_path(@basket)
  end

  def destroy
    @basket.destroy
    redirect_to baskets_path
  end

  private

  def basket_params
    params.require(:basket).permit(:name, :position, :nationality)
  end

  def set_basket
    @basket = Basket.find(params[:id])
  end
end


  # # Let's fake a database records
  # BASKETS = {
  #   1 => { name: "Tabuse", position: "Point Guard", nationality: "Japan" },
  #   2 => { name: "Watanabe", position: "Forward", nationality: "Japan" },
  #   3 => { name: "Harden", position: "Point Guard", nationality: "USA" }
  # }

  # def index
  #   if params[:player_type].blank?
  #     @baskets = BASKETS
  #   else
  #   @baskets = BASKETS.select do |id, basket|
  #     basket[:nationality] == params[:player_type]
  #     end
  #   end
  # end

  # def show
  #   @basket = BASKETS.find(params[:id])
  # end

  # def create
  #   @basket = BASKET.new(name: params[:name], address: params[:address])
  #   @basket.save
  # end

app/controllers/evaluations_controller.rb
class EvaluationsController < ApplicationController

  before_action :set_basket

  def new
    @evaluation = @basket.evaluations.build
  end

  def create
    @evaluation = Evaluation.new(evaluation_params)
    @evaluation.basket = @basket
    @evaluation.save
    redirect_to basket_path(@basket)
  end

  private

  def set_basket
    @basket = Basket.find(params[:basket_id])
  end

  def evaluation_params
    params.require(:evaluation).permit(:score, :comment)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/baskets_helper.rb
module BasketsHelper
end

app/helpers/evaluations_helper.rb
module EvaluationsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/admin/baskets/index.html.erb
<h1>My players</h1>
<div class="container">
  <div class="row">
    <h1>baskets</h1>
    <%= link_to "Add new player", new_basket_path %>
  </div>
  <div class="row">
    <div class="col-sm-12 col-md-4">
      <% @baskets.each do |basket| %>
        <h2><%= link_to basket.name, basket_path(basket) %></h2>
        <p><%= basket[:position] %></p>
        <p><%= basket.nationality %></p>
        <%= link_to "Delete", basket_path(basket), method: :delete %>
      <% end %>
      </div>
  </div>
</div>

app/views/baskets/_form.html.erb
<%= form_for @basket do |b| %>

  <% if @basket.errors.any? %>
    <ul>
      <%= @basket.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>

  <%= b.label :name, "Name" %>
  <%= b.text_field :name %>

  <%= b.label :position, "Position" %>
  <%= b.text_field :position %>

  <%= b.label :nationality, "Nationality" %>
  <%= b.text_field :nationality %>

  <%= b.label :average_score, "Average Score" %>
  <%= b.number_field :average_score %>

  <%= b.submit value="Update the player" %>

<% end %>

app/views/baskets/edit.html.erb
<%= render "form" %>


<!-- <form action="/baskets" method="patch">

  <input type="text" name="basket.name" value=>
  <input type="text" name="basket.position">
  <input type="text" name="basket.nationality">
  <input type="number" name="basket.average_score">
  <input type="submit" value="Create new player!">

</form>
 -->

app/views/baskets/index.html.erb
<div class="container">
  <div class="row">
    <h1>baskets</h1>
    <%= link_to "Add new player", new_basket_path %>
  </div>
  <div class="row">
    <div class="col-sm-12 col-md-4">
      <% @baskets.each do |basket| %>
        <h2><%= link_to basket.name, basket_path(basket) %></h2>
        <p><%= basket[:position] %></p>
        <p><%= basket.nationality %></p>
        <%= link_to "Delete", basket_path(basket), method: :delete %>
      <% end %>
      </div>
  </div>
</div>

app/views/baskets/new.html.erb
<%= render "form" %>


<!-- <form action="/baskets" method="post">

  <input type="text" name="basket.name">
  <input type="text" name="basket.position">
  <input type="text" name="basket.nationality">
  <input type="number" name="basket.average_score">
  <input type="submit" value="Create new player!">

</form>
 -->

app/views/baskets/show.html.erb
<h1><%= @basket.name %></h1>

<p>
  <%= @basket.position %>
</p>

<p>
  <%= @basket[:nationality] %>
</p>

<p>
  <%= @basket[:average_score] %>
</p>

<ul>
  <%= @basket.evaluations.each do |evaluation| %>
    <li><%= evaluation.score %></li>
    <li><%= evaluation.comment %></li>
  <% end %>
</ul>

<%= link_to "Back to the lists", baskets_path %>
<%= link_to "Edit this player!", edit_basket_path %>
<%= link_to "Team mate", team_mate_basket_path %>
<%= link_to "Add evaluation", new_basket_evaluation_path(@basket) %>

app/views/baskets/team_mate.html.erb
<h1>Team mate of <%= @basket.name %></h1>
<h2><%= @basket.team_mate %></h2>

app/views/baskets/top.html.erb
<h1>Top Players</h1>


<ul>
<%= @top_baskets.each do |player| %>
  <li><%= player.name %></li>
  <li><%= player.average_score %></li>
<% end %>
</ul>

app/views/evaluations/create.html.erb
<h1>Evaluations#create</h1>
<p>Find me in app/views/evaluations/create.html.erb</p>

app/views/evaluations/new.html.erb
<h1>Add evaluation for <%= @basket.name %></h1>

<%= form_for [@basket, @evaluation] do |f| %>

<% if @basket.errors.any? %>
  <ul>
    <%= @basket.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

  <%= f.label :score, "Score" %>
  <%= f.text_field :score %>
  <%= f.label :comment, "Comment" %>
  <%= f.text_field :comment %>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Libre</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>

    <footer>
      This is my first footer
    </footer>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.erb
<h1>Bienvenu à libre</h1>

<%= link_to "Go to see all players",  %>


<!-- <h2>Add a basket player</h2>
<form action="/baskets" method="post">
  <%#= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <input type="text" name="name" placeholder="Name">
  <input type="text" name="position" placeholder="Position">
  <input type="text" name="nationality" placeholder="Nationality">
  <input type="submit">
</form> -->